### ISSUE TITLE
Crash if empty stdout captured

### ISSUE THREAD

**Issue by rekka** [substantic/rain#27]
The following code crashes rain on Ubuntu 17.10:

```python
# crash.py
from rain.client import Client, tasks, blob

client = Client("localhost", 7210)

with client.new_session() as session:
    task = tasks.execute(["echo", "-n"], stdout=True)
    task.output.keep()

    session.submit()
    print(task.output.fetch().get_bytes())  # Should print b""
```

```
$ ./rain start --simple && python crash.py
$ ./rain start --simple && python crash.py
🌧  INFO 2018-04-09T09:51:14Z Starting Rain 0.2.0
🌧  INFO 2018-04-09T09:51:14Z Log directory: /tmp/rain-logs/worker-cmp-12356
🌧  INFO 2018-04-09T09:51:14Z Starting local server (0.0.0.0:7210)
🌧  INFO 2018-04-09T09:51:14Z Dashboard: http://cmp:8080/
🌧  INFO 2018-04-09T09:51:14Z Server pid = 12357
🌧  INFO 2018-04-09T09:51:14Z Process 'server' is ready
🌧  INFO 2018-04-09T09:51:14Z Starting 1 local worker(s)
🌧  INFO 2018-04-09T09:51:14Z Process 'worker-0' is ready
🌧  INFO 2018-04-09T09:51:14Z Rain started. 🌧
Traceback (most recent call last):
  File "crash.py", line 10, in <module>
    print(task.output.fetch().get_bytes())  # Should print b""
  File "/home/user/anaconda3/lib/python3.6/site-packages/rain/client/data.py", line 86, in fetch
    return self.session.fetch(self)
  File "/home/user/anaconda3/lib/python3.6/site-packages/rain/client/session.py", line 232, in fetch
    return self.client._fetch(dataobject)
  File "/home/user/anaconda3/lib/python3.6/site-packages/rain/client/client.py", line 125, in _fetch
    result = req.send().wait()
  File "capnp/lib/capnp.pyx", line 1932, in capnp.lib.capnp._RemotePromise.wait (capnp/lib/capnp.cpp:41109)
capnp.lib.capnp.KjException: capnp/rpc.c++:2092: disconnected: Peer disconnected.
stack: 0x7f6787fa9840 0x7f6787fa8140 0x7f6787f39db7 0x7f6787f23f03 0x7f6787f24027 0x7f6787f2440b 0x55751bc9501a 0x55751bd22bec 0x55751bd4719a 0x55751bd1c7db 0x55751bd22cc5 0x55751bd4719a 0x55751bd1c7db 0x55751bd22cc5 0x55751bd4719a 0x55751bd1c7db 0x55751bd22cc5 0x55751bd4719a 0x55751bd1d529 0x55751bd1e2cc 0x55751bd9aaf4 0x55751bd9aef1 0x55751bd9b0f4 0x55751bd9ec28 0x55751bc6671e 0x7f67893411c1 0x55751bd4dc98

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "crash.py", line 10, in <module>
    print(task.output.fetch().get_bytes())  # Should print b""
  File "/home/user/anaconda3/lib/python3.6/site-packages/rain/client/session.py", line 108, in __exit__
    self.close()
  File "/home/user/anaconda3/lib/python3.6/site-packages/rain/client/session.py", line 116, in close
    self.client._close_session(self)
  File "/home/user/anaconda3/lib/python3.6/site-packages/rain/client/client.py", line 163, in _close_session
    self._service.closeSession(session.session_id).wait()
  File "capnp/lib/capnp.pyx", line 1932, in capnp.lib.capnp._RemotePromise.wait (capnp/lib/capnp.cpp:41109)
capnp.lib.capnp.KjException: capnp/rpc.c++:2092: disconnected: Peer disconnected.
stack: 0x7f6787fa8140 0x7f6787f39db7 0x7f6787f23f03 0x7f6787f24027 0x7f6787f2440b 0x55751bc9501a 0x55751bd22bec 0x55751bd4719a 0x55751bd1c7db 0x55751bd22cc5 0x55751bd4719a 0x55751bd1c7db 0x55751bd22cc5 0x55751bd4719a 0x55751bd1ce4b 0x55751bc9539f 0x55751bc99ff3 0x55751bc951bb 0x55751bcb340d 0x55751bd48d22 0x55751bd1d529 0x55751bd1e2cc 0x55751bd9aaf4 0x55751bd9aef1 0x55751bd9b0f4 0x55751bd9ec28 0x55751bc6671e 0x7f67893411c1 0x55751bd4dc98
```

**Comment by spirali** [comment]
Thank you for reporting.
